"use client";
import { useState, useEffect, useRef } from "react";
import { HugeiconsIcon } from "@hugeicons/react";
import {
  Search01Icon,
  UserAdd01Icon,
  CheckIcon,
  QrCodeIcon,
  CircleXIcon,
  Delete04Icon,
} from "@hugeicons/core-free-icons";
import { useReactToPrint } from "react-to-print";
import { useParams } from "next/navigation";
import API from "../../../services/api";
import { toast } from "sonner";

const PrintableAttendeeList = ({ attendeesData, eventName, ref }) => {
  const checkedIn = attendeesData.filter((a) => a.isGoing);
  return (
    <div ref={ref} className="p-6 bg-white">
      <div className="text-center mb-6">
        <h1 className="text-xl font-bold text-gray-900 mb-2">
          {eventName ? `${eventName} Attendee List` : "Event Attendees List"}
        </h1>
        <p className="text-gray-600 text-sm">Checked-in: {checkedIn.length}</p>
        <p className="text-xs text-gray-500 mt-2">Generated on {new Date().toLocaleDateString()}</p>
      </div>
      <table className="w-full border-collapse border border-gray-300">
        <thead>
          <tr className="bg-gray-50">
            <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-sm">#</th>
            <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-sm">Name</th>
            <th className="border border-gray-300 px-3 py-2 text-left font-semibold text-sm">Email</th>
          </tr>
        </thead>
        <tbody>
          {checkedIn.map((a, i) => (
            <tr key={a.id} className={i % 2 === 0 ? "bg-white" : "bg-gray-50"}>
              <td className="border border-gray-300 px-3 py-2 text-sm">{i + 1}</td>
              <td className="border border-gray-300 px-3 py-2 font-medium text-sm">{a.name}</td>
              <td className="border border-gray-300 px-3 py-2 text-sm">{a.email}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className="mt-6 text-center text-xs text-gray-500">
        <p>Generated by Byro Ticketing Solutions</p>
      </div>
    </div>
  );
};

export default function Attendees() {
  const { slug } = useParams();
  const [attendeesData, setAttendeesData] = useState([]);
  const [eventName, setEventName] = useState("");
  const [attendeeCap, setAttendeeCap] = useState(null);
  const [checkedInCount, setCheckedInCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [searchTerm, setSearchTerm] = useState("");
  const [showCheckInModal, setShowCheckInModal] = useState(false);
  const [checkInValue, setCheckInValue] = useState("");
  const [checkingIn, setCheckingIn] = useState(false);

  const printRef = useRef();
  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: `Attendees-${new Date().toLocaleDateString()}`,
  });

  const loadAttendees = () => {
    if (!slug) return;
    setLoading(true);
    Promise.all([API.getEventAttendees(slug), API.getEvent(slug)])
      .then(([attendeesResp, eventResp]) => {
        const mapped = (attendeesResp.attendees || []).map((t) => ({
          id: t.ticket_id,
          name: t.current_owner_name || t.original_owner_name || "",
          email: t.current_owner_email || t.original_owner_email || "",
          isGoing: t.checked_in,
          paymentStatus: t.payment_status,
        }));
        setAttendeesData(mapped);
        setCheckedInCount(attendeesResp.checked_in_count || 0);
        setEventName(eventResp?.name || "");
        setAttendeeCap(eventResp?.capacity || null);
      })
      .catch((err) => {
        console.error("Error loading attendees:", err);
        setError("Failed to load attendees. You may not have permission.");
      })
      .finally(() => setLoading(false));
  };

  useEffect(() => { loadAttendees(); }, [slug]);

  const handleDelete = async (attendee) => {
    if (!confirm(`Remove ${attendee.name} from this event?`)) return;
    try {
      await API.cancelRegistration(attendee.id);
      toast.success(`${attendee.name} has been removed`);
      loadAttendees();
    } catch (err) {
      toast.error(err.message || "Failed to remove attendee");
    }
  };

  const handleCheckIn = async () => {
    if (!checkInValue.trim()) return;
    setCheckingIn(true);
    try {
      const result = await API.checkInAttendee(slug, checkInValue.trim());
      if (result.already_checked_in) {
        toast.info(`${result.attendee?.name || "Attendee"} is already checked in.`);
      } else {
        toast.success(`${result.attendee?.name || "Attendee"} checked in successfully!`);
        loadAttendees();
      }
      setCheckInValue("");
      setShowCheckInModal(false);
    } catch (err) {
      toast.error(err.message || "Check-in failed. Please verify the email or QR token.");
    } finally {
      setCheckingIn(false);
    }
  };

  const goingCount = attendeesData.filter((a) => a.isGoing).length;
  const filteredAttendees = attendeesData.filter(
    (a) =>
      a.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      a.email.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (loading) {
    return (
      <div className="p-4 flex justify-center py-12">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 text-center py-12">
        <p className="text-red-500 text-sm">{error}</p>
      </div>
    );
  }

  return (
    <div className="p-4 max-w-6xl mx-auto">
      {/* Stats */}
      <div className="flex justify-start mb-6 gap-4">
        <div className="bg-white border border-gray-200 rounded-lg shadow-sm p-4">
          <div className="flex justify-center space-x-8">
            <div className="flex flex-col items-center space-y-2">
              <div className="flex items-center space-x-2">
                <div className="w-4 h-4 bg-gray-400 rounded-sm flex items-center justify-center">
                  <HugeiconsIcon icon={UserAdd01Icon} size={12} color="white" />
                </div>
                <p className="text-gray-600 text-sm font-medium">Attendees Cap</p>
              </div>
              <p className="text-gray-900 font-bold text-xl">{attendeeCap ?? "—"}</p>
            </div>

            <div className="flex flex-col items-center space-y-2">
              <div className="flex items-center space-x-2">
                <div className="w-4 h-4 bg-green-500 rounded-sm flex items-center justify-center">
                  <HugeiconsIcon icon={CheckIcon} size={12} color="white" />
                </div>
                <p className="text-gray-600 text-sm font-medium">Checked In</p>
              </div>
              <p className="text-green-600 font-bold text-xl">{checkedInCount}</p>
            </div>

            <div className="flex flex-col items-center space-y-2">
              <div className="flex items-center space-x-2">
                <div className="w-4 h-4 bg-blue-500 rounded-sm flex items-center justify-center">
                  <HugeiconsIcon icon={UserAdd01Icon} size={12} color="white" />
                </div>
                <p className="text-gray-600 text-sm font-medium">Registered</p>
              </div>
              <p className="text-blue-600 font-bold text-xl">{attendeesData.length}</p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex flex-col space-y-2">
          <button
            onClick={() => setShowCheckInModal(true)}
            className="flex items-center gap-2 bg-[#007AFF] hover:bg-[#0056CC] text-white font-medium px-4 py-2 rounded-lg transition-colors text-sm"
          >
            <HugeiconsIcon icon={QrCodeIcon} size={16} />
            Check In
          </button>
          <button
            onClick={handlePrint}
            className="bg-gray-100 hover:bg-gray-200 text-gray-700 font-medium px-4 py-2 rounded-lg transition-colors text-sm"
          >
            Export
          </button>
        </div>
      </div>

      {/* Header + Search */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-gray-900 font-bold text-xl">Attendees</h1>
          <p className="text-gray-500 text-sm">{attendeesData.length} registered</p>
        </div>
        <div className="relative">
          <HugeiconsIcon icon={Search01Icon} size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
          <input
            type="search"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-gray-50 border-0 pl-9 pr-3 py-2 rounded-lg text-gray-900 placeholder-gray-500 outline-none focus:ring-2 focus:ring-gray-300 w-64 text-sm"
            placeholder="search for attendee..."
          />
        </div>
      </div>

      {/* List */}
      <div className="bg-white border border-gray-100 rounded-lg shadow-sm overflow-hidden">
        {filteredAttendees.length === 0 ? (
          <div className="text-center py-8">
            <h3 className="text-base font-semibold text-gray-900 mb-2">
              {searchTerm ? "No attendees found" : "No registered attendees yet"}
            </h3>
            <p className="text-gray-500 text-sm">
              {searchTerm ? "Try adjusting your search terms" : "Attendees will appear here once they register."}
            </p>
          </div>
        ) : (
          <div className="divide-y divide-gray-100">
            {filteredAttendees.map((attendee) => (
              <div key={attendee.id} className="flex items-center justify-between p-4 hover:bg-gray-50">
                <div className="flex items-center space-x-3 flex-1">
                  <div className="w-8 h-8 bg-gradient-to-br from-[#007AFF] to-[#0056CC] rounded-full flex items-center justify-center text-white font-semibold text-sm">
                    {(attendee.name || "?").charAt(0).toUpperCase()}
                  </div>
                  <h3 className="text-gray-900 font-medium text-sm">{attendee.name}</h3>
                </div>
                <div className="flex-1 min-w-0 px-4">
                  <p className="text-gray-600 text-sm">{attendee.email}</p>
                </div>
                <span
                  className={`inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium ${
                    attendee.isGoing ? "bg-green-100 text-green-700" : "bg-blue-100 text-blue-700"
                  }`}
                >
                  {attendee.isGoing ? "Checked In" : "Registered"}
                </span>
                <button
                  onClick={() => handleDelete(attendee)}
                  className="ml-3 p-1.5 text-gray-400 hover:text-red-500 transition-colors"
                  title="Remove attendee"
                >
                  <HugeiconsIcon icon={Delete04Icon} size={18} />
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Check-in Modal */}
      {showCheckInModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-full max-w-sm mx-4 shadow-xl">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-semibold">Check In Attendee</h3>
              <button onClick={() => setShowCheckInModal(false)}>
                <HugeiconsIcon icon={CircleXIcon} size={20} className="text-gray-400 hover:text-gray-600" />
              </button>
            </div>
            <p className="text-sm text-gray-500 mb-4">
              Enter the attendee&apos;s email address or paste their QR token.
            </p>
            <input
              type="text"
              value={checkInValue}
              onChange={(e) => setCheckInValue(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleCheckIn()}
              className="w-full px-3 py-2 border border-gray-300 rounded-lg text-gray-900 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 mb-4"
              placeholder="email@example.com or QR token"
              autoFocus
            />
            <div className="flex gap-3">
              <button
                onClick={() => setShowCheckInModal(false)}
                className="flex-1 px-4 py-2 text-gray-600 bg-gray-100 rounded-lg hover:bg-gray-200 text-sm"
              >
                Cancel
              </button>
              <button
                onClick={handleCheckIn}
                disabled={checkingIn || !checkInValue.trim()}
                className="flex-1 px-4 py-2 bg-[#007AFF] text-white rounded-lg hover:bg-[#0056CC] disabled:opacity-50 text-sm font-medium"
              >
                {checkingIn ? "Checking in..." : "Check In"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Hidden printable */}
      <div style={{ display: "none" }}>
        <PrintableAttendeeList
          ref={printRef}
          attendeesData={attendeesData}
          eventName={eventName}
        />
      </div>
    </div>
  );
}
