# Generated by Django 5.2 on 2025-05-16 12:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('day', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('virtual_link', models.URLField(blank=True, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.IntegerField(null=True)),
                ('transferable', models.BooleanField(default=False)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('timezone', models.CharField(default='GMT+0:00 Lagos', max_length=50)),
                ('hosted_by', models.CharField(default='Byro africa', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success_message', models.TextField(default='Thank you for your payment!')),
                ('inactive_message', models.TextField(blank=True, default='This payment link is no longer active.')),
                ('redirect_url', models.URLField(blank=True, default='')),
                ('branding_image', models.ImageField(blank=True, null=True, upload_to='payment_branding/')),
                ('payment_limit', models.PositiveIntegerField(blank=True, default=0, help_text='0 means unlimited')),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='PrivyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privy_id', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_owner_name', models.CharField(max_length=255)),
                ('original_owner_email', models.EmailField(max_length=254)),
                ('current_owner_name', models.CharField(max_length=255)),
                ('current_owner_email', models.EmailField(max_length=254)),
                ('is_transferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bryo.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_name', models.CharField(blank=True, null=True)),
                ('from_user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_user_name', models.CharField(max_length=255)),
                ('to_user_email', models.EmailField(max_length=254)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('transfer_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='bryo.ticket')),
            ],
            options={
                'ordering': ['-transferred_at'],
            },
        ),
    ]
