# Generated by Django 5.2 on 2025-05-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
