# Generated by Django 5.2 on 2025-06-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0003_alter_event_name_alter_event_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
