# Generated by Django 5.2 on 2025-07-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='privyuser',
            name='password',
            field=models.CharField(default='unusable', max_length=128),
        ),
        migrations.AlterField(
            model_name='privyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='privyuser',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
