# Generated by Django 5.2 on 2025-10-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0005_alter_event_options_event_is_active_event_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettransfer',
            name='from_user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
