# Generated by Django 5.2 on 2025-10-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0006_alter_tickettransfer_from_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('web3_crypto', 'Web3 & Crypto'), ('entertainment', 'Entertainment'), ('art_culture', 'Art & Culture'), ('fitness', 'Fitness'), ('conference', 'Conference'), ('technology', 'Technology'), ('other', 'Other')], db_index=True, default='other', help_text='Event category for filtering', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', '-created_at'], name='bryo_event_categor_53998e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_active', '-created_at'], name='bryo_event_is_acti_6ec70f_idx'),
        ),
    ]
