# Generated by Django 5.2 on 2025-11-10 17:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0007_event_category_event_bryo_event_categor_53998e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('paystack_reference', models.CharField(max_length=255, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=255, null=True)),
                ('paystack_authorization_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], default='pending', max_length=20)),
                ('channel', models.CharField(blank=True, choices=[('card', 'Card'), ('bank', 'Bank'), ('ussd', 'USSD'), ('qr', 'QR'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bryo.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PaymentSettings',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('free', 'Free'), ('pending', 'Payment Pending'), ('paid', 'Paid'), ('failed', 'Payment Failed')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='ticket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bryo.ticket'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paystack_reference'], name='bryo_paymen_paystac_ad7fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='bryo_paymen_status_a1cec3_idx'),
        ),
    ]
