# Generated by Django 4.2.17 on 2026-04-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bryo', '0008_payment_delete_paymentsettings_ticket_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='auth_provider',
            field=models.CharField(blank=True, choices=[('privy', 'Privy'), ('web3auth', 'Web3Auth')], default='privy', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
